### ISSUE TITLE
AUR update doesn't update to the advertised version

### ISSUE THREAD

**Issue by HerrNaN** [ViddeM/printit#1]
The upgrade says there is a new version `1.1.1-1` but when it comes to actually performing the upgrade it only upgrades to `v1.0.2.r3.gf49863a-1`
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Missing AUR Packages:  jdk10-openjdk  jre10-openjdk  jre10-openjdk-headless  openjdk10-doc  openjdk10-src  python2-apsw  python2-css-parser  python2-html2text  python2-html5-parser  python2-markdown  python2-mechanize  python2-netifaces  python2-pychm  python2-pyqt5  python2-pyqtwebengine  python2-regex  python2-sip-pyqt5  python2-unrardll
 -> Orphaned AUR Packages:  auctex  auctex-latexmk
 -> Flagged Out Of Date AUR Packages:  feedthebeast  insomnia  nouveau-fw  spotify
:: 1 Packages to upgrade.
1  aur/printit-git  v1.0.2.r3.gf49863a-1 -> 1.1.1-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  printit-git-1.1.1-1

  1 printit-git                      (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): printit-git
  1 printit-git                      (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: printit-git
==> Making package: printit-git 1.1.1-1 (Fri 25 Sep 2020 11:42:09 AM CEST)
==> Retrieving sources...
  -> Updating printit-git git repo...
Fetching origin
==> Validating source files with sha256sums...
    printit-git ... Skipped
==> Making package: printit-git 1.1.1-1 (Fri 25 Sep 2020 11:42:10 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating printit-git git repo...
Fetching origin
==> Validating source files with sha256sums...
    printit-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of printit-git git repo...
Cloning into 'printit-git'...
done.
==> Starting pkgver()...
==> Updated version: printit-git v1.0.2.r3.gf49863a-1
==> Sources are ready.
==> Making package: printit-git v1.0.2.r3.gf49863a-1 (Fri 25 Sep 2020 11:42:12 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
 -> printit-git-v1.0.2.r3.gf49863a-1 already made -- skipping build
 -> Found git repo: github.com/viddem/printit.git
loading packages...
warning: printit-git-v1.0.2.r3.gf49863a-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version           New Version           Net Change

printit-git  v1.0.2.r3.gf49863a-1  v1.0.2.r3.gf49863a-1    0.00 MiB

Total Installed Size:  0.04 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                 [----------------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                               [----------------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                                    [----------------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                              [----------------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                                            [----------------------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling printit-git                                                                                                 [----------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

**Comment by ViddeM** [comment]
Should be solved as of https://github.com/ViddeM/printit/releases/tag/v1.2.4

**Comment by HerrNaN** [comment]
Still not resolved, although some progress have been made:
```
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
 there is nothing to do
:: Searching databases for updates...
:: Searching AUR for updates...
 -> Missing AUR Packages:  jdk10-openjdk  jre10-openjdk  jre10-openjdk-headless  openjdk10-doc  openjdk10-src  python2-css-parser  python2-html2text  python2-html5-parser  python2-markdown  python2-mechanize  python2-netifaces  python2-pychm  python2-pyqt5  python2-pyqtwebengine  python2-regex  python2-sip-pyqt5  python2-unrardll
 -> Orphaned AUR Packages:  auctex  auctex-latexmk
 -> Flagged Out Of Date AUR Packages:  feedthebeast  insomnia  nouveau-fw  spotify
:: 1 Packages to upgrade.
1  aur/printit-git  v1.2.5.r0.gead3b82-1 -> 1.2.5-1
==> Packages to exclude: (eg: "1 2 3", "1-3", "^4" or repo name)
==> 
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:1]  printit-git-1.2.5-1

  1 printit-git                      (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: PKGBUILD up to date, Skipping (1/1): printit-git
  1 printit-git                      (Installed) (Build Files Exist)
==> Diffs to show?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
:: (1/1) Parsing SRCINFO: printit-git
==> Making package: printit-git 1.2.5-1 (Sat 26 Sep 2020 10:38:48 AM CEST)
==> Retrieving sources...
  -> Updating printit-git git repo...
Fetching origin
==> Validating source files with sha256sums...
    printit-git ... Skipped
==> Making package: printit-git 1.2.5-1 (Sat 26 Sep 2020 10:38:49 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating printit-git git repo...
Fetching origin
==> Validating source files with sha256sums...
    printit-git ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of printit-git git repo...
Cloning into 'printit-git'...
done.
==> Starting pkgver()...
==> Updated version: printit-git v1.2.5.r0.gead3b82-1
==> Sources are ready.
==> Making package: printit-git v1.2.5.r0.gead3b82-1 (Sat 26 Sep 2020 10:38:51 AM CEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Sources are ready.
 -> printit-git-v1.2.5.r0.gead3b82-1 already made -- skipping build
 -> Found git repo: github.com/viddem/printit.git
loading packages...
warning: printit-git-v1.2.5.r0.gead3b82-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)  Old Version           New Version           Net Change

printit-git  v1.2.5.r0.gead3b82-1  v1.2.5.r0.gead3b82-1    0.00 MiB

Total Installed Size:  0.04 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                 [----------------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                               [----------------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                                    [----------------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                              [----------------------------------------------------------------------------] 100%
(1/1) checking available disk space                                                                                            [----------------------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling printit-git                                                                                                 [----------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

The problem seems to be that you overwrite `pkgver` by defining `pkgver()` in the `PKGBUILD` so when building the version will be updated. Try either only using that function or only manually changing the `pkgver` variable :+1:

**Comment by HerrNaN** [comment]
For more information about how the pkgver works, read [the arch wiki page](https://wiki.archlinux.org/index.php/PKGBUILD#pkgver)

**Comment by HerrNaN** [comment]
Seems to be resolved by [v1.3.0](https://github.com/ViddeM/printit/releases/tag/v1.3.0)
